name: asset_fill
description: Package for generating assets in pubspec.yaml. Iterates throw all the subdirectories in assets folder.
version: 2.0.0
repository: https://github.com/L3odr0id/asset_fill

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  yaml_edit: ^2.0.1
