name: asset_fill
description: A package to generate assets in pubspec.yaml. Goes throw all the subdirectories in assets folder.
version: 1.0.2
repository: https://github.com/L3odr0id/asset_fill

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  yaml_edit: ^2.0.1

